services:

  ollama-service:
    image: ollama/ollama:0.5.4
    volumes:
      - ./ollama-data:/root/.ollama
    ports:
      - 11434:11434

  download-tools-llm:
    image: curlimages/curl:8.6.0
    entrypoint: ["curl", "ollama-service:11434/api/pull", "-d", "{\"name\": \"allenporter/xlam:1b\"}"]
    depends_on:
      ollama-service:
        condition: service_started

  mcp-server:
    image: golang:1.23.4-alpine
    entrypoint: 
      - /bin/sh
      - -c
      - cd /app && go mod tidy && go run main.go
    environment:
      - HTTP_PORT=5050
    ports:
      - 8080:5050
    volumes:
      - ./:/app


  mcp-host:
    image: golang:1.23.4-alpine
    entrypoint: 
      - /bin/sh
      - -c
      - cd /app/samples/simple-mcp-host && go mod tidy && go run main.go
    environment:
      - OLLAMA_HOST=http://ollama-service:11434
      - MCP_SERVER_HOST=http://mcp-server:5050
    volumes:
      - ./:/app
    depends_on:
      download-tools-llm:
        condition: service_completed_successfully
      mcp-server:
        condition: service_started # healthcheck ?

  #ubuntu:
  #  image: ubuntu:22.04
  #  tty: true
  #  command: tail -f /dev/null
  #  volumes:
  #    - ./:/app    
