services:

  mcp-server:
    build:
      context: "."
      platforms:
        - "linux/amd64"
        - "linux/arm64"
    image: amphipod
    entrypoint: ["./amphipod"]
    environment:
      - HTTP_PORT=8080
      - USE_HTTPS=false
      - REQUIRE_AUTH=false
    ports:
      - 8080:8080
    volumes:
      - ./:/app
